### Get current tax position
GET http://localhost:3000/tax-position?date=2026-08-03T12:30:00Z

### Create Tax Payment
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "eventType": "TAX_PAYMENT",
  "date": "2026-08-02T14:40:00Z",
  "amount": 1500
}


### Create Sales Event
POST http://localhost:3000/transactions
Content-Type: application/json

{
  "eventType": "SALES",
  "date": "2026-08-02T12:30:00Z",
  "invoiceId": "Invoice 1",
  "items": [{
      "itemId": "Item 1",
      "cost": 1099,
      "taxRate": 0.2
    },
    {
      "itemId": "Item 2",
      "cost": 5000,
      "taxRate": 0.2
    },
    {
      "itemId": "Item 3",
      "cost": 1200,
      "taxRate": 0.2
    }
  ]
}


### Amend Sale Event
PATCH  http://localhost:3000/sale
Content-Type: application/json

{
  "date": "2026-08-03T17:29:39Z",
  "invoiceId": "Invoice 1",
  "itemId": "Item 3",
  "cost": 1000,
  "taxRate": 0.28
}
